### ISSUE TITLE
Nefunkční přehrávání

### ISSUE THREAD

**Issue by Vasek79** [kodi-czsk/plugin.video.dmd-czech.aktualne#11]
Několik dní nefunguje přehrávání z "Aktuálně". Seznam se načte, ale po vybrání videa se zobrazí chyba. Stejný stav na dvou zařízeních. Zřejmě nějaká změna v API, ale tomu moc nerozumím. Jak jsem vyčetl na netu, tak to není jen u mě.
Totéž u addonu DVTV - stejný zdroj, stejný problém...

S pozdravem Vašek

**Comment by ToKroCZ** [comment]
Změnil se přehrávač na webu, pravděpodobně to souvisí s tím.

**Comment by stefanides** [comment]
Nj, formát vypadá, že se hodně změnil. Zkusil jsem to trochu přepsat, viz níže. 
Live streamy pořád nefungujou (issue #9), ale nejspíš by to tam šlo taky najít :-)
```
addon.py.patch:
15a16
> import json
136c137,143
< 		videos = re.compile('{[^i]*?image.*?sources:[^]]*?][^}]*?}', re.S).findall(httpdata)
---
> 		title = re.compile('<meta property="og:title" content=".*">').search(httpdata).group(0)
> 		title = re.sub('<meta property="og:title" content="', '', title).replace('">', '')
> 		image = re.compile('<meta property="og:image" content=".*">').search(httpdata).group(0)
> 		image = re.sub('<meta property="og:image" content="', '', image).replace('">', '')
> 		description = re.compile('<meta property="og:description" content=".*">').search(httpdata).group(0)
> 		description = re.sub('<meta property="og:description" content="', '', description).replace('">', '')
> 		videos = re.compile('tracks: {.*}]},', re.S).findall(httpdata)
141c148
< 				twice = True        
---
> 				twice = True
143,159c150,169
< 				image = 'http:' + re.compile('image: ?\'([^\']*?)\'').search(video).group(1).strip()
< 				title = _htmlParser_.unescape(re.compile('title: ?\'([^\']*?\'').search(video).group(1).strip())
< 				description = re.compile('description: ?\'([^\']*?)\'').search(video);
< 				if description:				
< 					description = _htmlParser_.unescape(description.group(1).strip())
< 				sources = re.compile('sources: ?(\[[^\]]*?])', re.S).search(video).group(1)
< 				if sources:		
< 					versions = re.compile('{[^}]*?}', re.S).findall(sources)
< 					if versions:
< 						for version in versions:
< 							url = re.compile('"file":"([^"]*)"').search(version).group(1).replace('\/','/').strip()
< 							mime = re.compile('"type":"([^"]*)"').search(version).group(1).replace('\/','/').strip()
< 							quality = re.compile('"label":"([^"]*)"').search(version).group(1).strip()
< 							li = xbmcgui.ListItem(title)
< 							li.setThumbnailImage(image)					
< 							li.addStreamInfo('video', {'language': 'cs'})
< 							if (quality == _quality_ and mime == _format_):
---
> 				video = re.sub(re.compile('\sadverttime:.*', re.S), '', video) # live streams workaround
> 				video = video.replace('tracks: ', '')
> 				video = re.sub(r'[,\w]*$','',video)
> 				try:
> 					detail = json.loads(video)
> 				except ValueError:
> 					showErrorNotification(_lang_(30005))
> 					return
> 				if detail.has_key('MP4'):
> 					sources = detail['MP4']
> 					for version in sources:
> 						url = version['src']
> 						mime = version['type']
> 						quality = version['label']
> 						li = xbmcgui.ListItem(title)
> 						li.setThumbnailImage(image)
> 						li.addStreamInfo('video', {'language': 'cs'})
> 						if (quality == _quality_ and mime == _format_):
> 							xbmc.PlayList(1).add(url, li)
> 							if twice:
161,162d170
< 								if twice:
< 									xbmc.PlayList(1).add(url, li)  		
```

**Comment by stefanides** [comment]
A bude se jím někdo zabývat? :-) Viz pull #10 a půl roku ticho..

**Comment by me2d09** [comment]
Večer na to kdyžtak kouknu, jestli to nestihne dřív opravit někdo jinej.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jose1711** [comment]
> A bude se jím někdo zabývat? :-) Viz pull #10 a půl roku ticho..

aj tak stale lepsie to mat vo svojom forku fixnute ako nechat povalovat patche v komentaroch k issue.

**Comment by stefanides** [comment]
> aj tak stale lepsie to mat vo svojom forku fixnute ako nechat povalovat patche v komentaroch k issue.
Jestli někdo slíbí, že to mergne, tak to klidně doklikám do PR. Jinak je to ztráta času :-)

**Comment by jose1711** [comment]
ja bohuzial write prava nemam. ale napisem @lzoubek -ovi

**Comment by brozikcz** [comment]
Taky mam prava na merge :)

**Comment by stefanides** [comment]
Tož testujte a mergujte. Snad nechybí nic zásadního :-)

**Comment by me2d09** [comment]
Opravil jsem tam několik bugů - viz mé commity. Teď to vypadá funkčně - prosím vyzkoušejte to ještě někdo a já to pak mergnu.

**Comment by stefanides** [comment]
U mně funguje (zkouším jen DVTV), dík

**Comment by ToKroCZ** [comment]
Zkusil jsem i jiné pořady než DVTV a vypadá to funkční. Díky! :) 

_A jen takový velmi drzý návrh, obdobný problém[ teď potkal Primu Play](https://www.xbmc-kodi.cz/prispevek-prima-play?page=2) a lzoubek to nemá do Vánoc čas fixnout, nechtěl by se na to někdo z vás podívat, když vám to tak jde? 👍 Kdybych to uměl, tak to rád opravím sám, ale bohužel..._

**Comment by stefanides** [comment]
> _A jen takový velmi drzý návrh, obdobný problém[ teď potkal Primu Play](https://www.xbmc-kodi.cz/prispevek-prima-play?page=2) a alladin to nemá do Vánoc čas fixnout, nechtěl by se na to někdo z vás podívat, když vám to tak jde? +1 

Jestli toho změnili víc, vč. procházení katalogu, pak to může být fakt na dlouho :-( 

> Kdybych to uměl, tak to rád opravím sám, ale bohužel...

Pro mně je to taky první úprava v kodi a pythonu :-)
